version: '3'

services:
  node-app:
    container_name: node-app-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    environment:
      - NODE_ENV=development
    volumes:
      - ./.env.development:/data/app/.env.development
      - ./src:/data/app/src
      - ./nodemon.json:/data/app/nodemon.json
    command: yarn dev -L
