# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: nodejs-master

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    name: Test

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Create test Environment
        run: cp .env.example .env.test

      - name: Run e2e test
        uses: borales/actions-yarn@v4
        with:
          cmd: test:e2e

      - name: Run unit test
        uses: borales/actions-yarn@v4
        with:
          cmd: test:unit
